chore(deps): update all non-major dependencies (#49)
[![Mend Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [@types/node](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node) ([source](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/node)) | [`20.10.5` -> `20.11.17`](https://renovatebot.com/diffs/npm/@types%2fnode/20.10.5/20.11.17) | [![age](https://developer.mend.io/api/mc/badges/age/npm/@types%2fnode/20.11.17?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@types%2fnode/20.11.17?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@types%2fnode/20.10.5/20.11.17?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@types%2fnode/20.10.5/20.11.17?slim=true)](https://docs.renovatebot.com/merge-confidence/) |
| [@types/react](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react) ([source](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/react)) | [`18.2.45` -> `18.2.55`](https://renovatebot.com/diffs/npm/@types%2freact/18.2.45/18.2.55) | [![age](https://developer.mend.io/api/mc/badges/age/npm/@types%2freact/18.2.55?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@types%2freact/18.2.55?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@types%2freact/18.2.45/18.2.55?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@types%2freact/18.2.45/18.2.55?slim=true)](https://docs.renovatebot.com/merge-confidence/) |
| [@types/react-dom](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-dom) ([source](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/react-dom)) | [`18.2.18` -> `18.2.19`](https://renovatebot.com/diffs/npm/@types%2freact-dom/18.2.18/18.2.19) | [![age](https://developer.mend.io/api/mc/badges/age/npm/@types%2freact-dom/18.2.19?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@types%2freact-dom/18.2.19?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@types%2freact-dom/18.2.18/18.2.19?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@types%2freact-dom/18.2.18/18.2.19?slim=true)](https://docs.renovatebot.com/merge-confidence/) |
| [@vercel/analytics](https://togithub.com/vercel/analytics) ([source](https://togithub.com/vercel/analytics/tree/HEAD/packages/web)) | [`1.1.1` -> `1.1.3`](https://renovatebot.com/diffs/npm/@vercel%2fanalytics/1.1.1/1.1.3) | [![age](https://developer.mend.io/api/mc/badges/age/npm/@vercel%2fanalytics/1.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@vercel%2fanalytics/1.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@vercel%2fanalytics/1.1.1/1.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@vercel%2fanalytics/1.1.1/1.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/) |
| [prettier](https://prettier.io) ([source](https://togithub.com/prettier/prettier)) | [`3.1.1` -> `3.2.5`](https://renovatebot.com/diffs/npm/prettier/3.1.1/3.2.5) | [![age](https://developer.mend.io/api/mc/badges/age/npm/prettier/3.2.5?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/prettier/3.2.5?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/prettier/3.1.1/3.2.5?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/prettier/3.1.1/3.2.5?slim=true)](https://docs.renovatebot.com/merge-confidence/) |
| [vite](https://vitejs.dev) ([source](https://togithub.com/vitejs/vite/tree/HEAD/packages/vite)) | [`5.0.12` -> `5.1.1`](https://renovatebot.com/diffs/npm/vite/5.0.12/5.1.1) | [![age](https://developer.mend.io/api/mc/badges/age/npm/vite/5.1.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/vite/5.1.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/vite/5.0.12/5.1.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/vite/5.0.12/5.1.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) |
| [zustand](https://togithub.com/pmndrs/zustand) | [`4.4.7` -> `4.5.0`](https://renovatebot.com/diffs/npm/zustand/4.4.7/4.5.0) | [![age](https://developer.mend.io/api/mc/badges/age/npm/zustand/4.5.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/zustand/4.5.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/zustand/4.4.7/4.5.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/zustand/4.4.7/4.5.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) |

---

### Release Notes

<details>
<summary>vercel/analytics (@&#8203;vercel/analytics)</summary>

### [`v1.1.3`](https://togithub.com/vercel/analytics/releases/tag/1.1.3)

[Compare Source](https://togithub.com/vercel/analytics/compare/1.1.2...1.1.3)

#### What's Changed

-   Server events can now be sent when deployment protection is enabled by [@&#8203;tobiaslins](https://togithub.com/tobiaslins) in [https://github.com/vercel/analytics/pull/129](https://togithub.com/vercel/analytics/pull/129)

**Full Changelog**: https://github.com/vercel/analytics/compare/1.1.2...1.1.3

### [`v1.1.2`](https://togithub.com/vercel/analytics/releases/tag/1.1.2)

[Compare Source](https://togithub.com/vercel/analytics/compare/1.1.1...1.1.2)

#### What's Changed

-   Fix server side tracking for Remix actions by [@&#8203;tobiaslins](https://togithub.com/tobiaslins) in [https://github.com/vercel/analytics/pull/124](https://togithub.com/vercel/analytics/pull/124)

**Full Changelog**: https://github.com/vercel/analytics/compare/1.1.1...1.1.2

</details>

<details>
<summary>prettier/prettier (prettier)</summary>

### [`v3.2.5`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#325)

[Compare Source](https://togithub.com/prettier/prettier/compare/3.2.4...3.2.5)

[diff](https://togithub.com/prettier/prettier/compare/3.2.4...3.2.5)

##### Support Angular inline styles as single template literal ([#&#8203;15968](https://togithub.com/prettier/prettier/pull/15968) by [@&#8203;sosukesuzuki](https://togithub.com/sosukesuzuki))

[Angular v17](https://blog.angular.io/introducing-angular-v17-4d7033312e4b) supports single string inline styles.



```ts
// Input
@&#8203;Component({
  template: `<div>...</div>`,
  styles: `h1 { color: blue; }`,
})
export class AppComponent {}

// Prettier 3.2.4
@&#8203;Component({
  template: `<div>...</div>`,
  styles: `h1 { color: blue; }`,
})
export class AppComponent {}

// Prettier 3.2.5
@&#8203;Component({
  template: `<div>...</div>`,
  styles: `
    h1 {
      color: blue;
    }
  `,
})
export class AppComponent {}

```

##### Unexpected embedded formatting for Angular template ([#&#8203;15969](https://togithub.com/prettier/prettier/pull/15969) by [@&#8203;JounQin](https://togithub.com/JounQin))

Computed template should not be considered as Angular component template



```ts
// Input
const template = "foobar";

@&#8203;Component({
  [template]: `<h1>{{       hello }}</h1>`,
})
export class AppComponent {}

// Prettier 3.2.4
const template = "foobar";

@&#8203;Component({
  [template]: `<h1>{{ hello }}</h1>`,
})
export class AppComponent {}

// Prettier 3.2.5
const template = "foobar";

@&#8203;Component({
  [template]: `<h1>{{       hello }}</h1>`,
})
export class AppComponent {}
```

##### Use `"json"` parser for `tsconfig.json` by default ([#&#8203;16012](https://togithub.com/prettier/prettier/pull/16012) by [@&#8203;sosukesuzuki](https://togithub.com/sosukesuzuki))

In [v2.3.0](https://prettier.io/blog/2024/01/12/3.2.0#new-jsonc-parser-added-15831httpsgithubcomprettierprettierpull15831-by-fiskerhttpsgithubcomfisker), we introduced `"jsonc"` parser which adds trialing comma **by default**.

When adding a new parser we also define how it will be used based on the [`linguist-languages`](https://www.npmjs.com/package/linguist-languages) data.

`tsconfig.json` is a special file used by [TypeScript](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#using-tsconfigjson-or-jsconfigjson), it uses `.json` file extension, but it actually uses the [JSON with Comments](https://code.visualstudio.com/docs/languages/json#\_json-with-comments) syntax. However, we found that there are many third-party tools not recognize it correctly because of the confusing `.json` file extension.

We decide to treat it as a JSON file for now to avoid the extra configuration step.

To keep using the `"jsonc"` parser for your `tsconfig.json` files, add the following to your `.pretterrc` file

```json
{
  "overrides": [
    {
      "files": ["tsconfig.json", "jsconfig.json"],
      "options": {
        "parser": "jsonc"
      }
    }
  ]
}
```



```
```

### [`v3.2.4`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#324)

[Compare Source](https://togithub.com/prettier/prettier/compare/3.2.3...3.2.4)

[diff](https://togithub.com/prettier/prettier/compare/3.2.3...3.2.4)

##### Fix incorrect parser inference ([#&#8203;15947](https://togithub.com/prettier/prettier/pull/15947) by [@&#8203;fisker](https://togithub.com/fisker))

Files like `.eslintrc.json` were incorrectly formatted as JSONC files.



```jsx
// Input
prettier --file-info .eslintrc.json
{ "ignored": false, "inferredParser": "jsonc" }

// Prettier 3.2.4
prettier --file-info .eslintrc.json
{ "ignored": false, "inferredParser": "json" }
```

### [`v3.2.3`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#323)

[Compare Source](https://togithub.com/prettier/prettier/compare/3.2.2...3.2.3)

[diff](https://togithub.com/prettier/prettier/compare/3.2.2...3.2.3)

##### Throw errors for invalid code ([#&#8203;15881](https://togithub.com/prettier/prettier/pull/15881) by [@&#8203;fisker](https://togithub.com/fisker), [@&#8203;Josh-Cena](https://togithub.com/Josh-Cena), [@&#8203;auvred](https://togithub.com/auvred))



```ts
// Input
1++;

// Prettier 3.2.2
1++;

// Prettier 3.2.3
SyntaxError: Invalid left-hand side expression in unary operation (1:1)
> 1 | 1++;
    | ^
```



```ts
// Input
try {} catch (error = 1){}

// Prettier 3.2.2
try {
} catch (error) {}

// Prettier 3.2.3
SyntaxError: Catch clause variable cannot have an initializer. (1:23)
> 1 | try {} catch (error = 1){}
    |                       ^
```

##### Fix parser inference ([#&#8203;15927](https://togithub.com/prettier/prettier/pull/15927) by [@&#8203;fisker](https://togithub.com/fisker))



```console
// Prettier 3.2.2
prettier --file-info tsconfig.json
{ "ignored": false, "inferredParser": "json" }

// Prettier 3.2.3
prettier --file-info tsconfig.json
{ "ignored": false, "inferredParser": "jsonc" }
```

### [`v3.2.2`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#322)

[Compare Source](https://togithub.com/prettier/prettier/compare/3.2.1...3.2.2)

[diff](https://togithub.com/prettier/prettier/compare/3.2.1...3.2.2)

##### Fix crash when parsing template literal CSS in a JSX style tag using a spread attribute ([#&#8203;15896](https://togithub.com/prettier/prettier/pull/15896) by [@&#8203;eelco](https://togithub.com/eelco))

For example this code would crash before:



```jsx
<style {...spread}>{`.{}`}</style>
```

##### Fix formatting error on optional call expression and member chain ([#&#8203;15920](https://togithub.com/prettier/prettier/pull/15920) by [@&#8203;sosukesuzuki](https://togithub.com/sosukesuzuki))



```jsx
// Input
a(() => {}, c?.d());

// Prettier 3.2.1
TypeError: Cannot read properties of undefined (reading 'type')

// Prettier 3.2.2
a(() => {}, c?.d());
```

### [`v3.2.1`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#321)

[Compare Source](https://togithub.com/prettier/prettier/compare/3.2.0...3.2.1)

[diff](https://togithub.com/prettier/prettier/compare/3.2.0...3.2.1)

##### Fix formatting error on member chain ([#&#8203;15915](https://togithub.com/prettier/prettier/pull/15915) by [@&#8203;sosukesuzuki](https://togithub.com/sosukesuzuki))



```jsx
// Input
test().test2().test2(thing?.something);

// Prettier 3.2.0
TypeError: Cannot read properties of undefined (reading 'type')

// Prettier 3.2.1
test().test2().test2(thing?.something);

```

### [`v3.2.0`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#320)

[Compare Source](https://togithub.com/prettier/prettier/compare/3.1.1...3.2.0)

[diff](https://togithub.com/prettier/prettier/compare/3.1.1...3.2.0)

🔗 [Release Notes](https://prettier.io/blog/2024/01/13/3.2.0.html)

</details>

<details>
<summary>vitejs/vite (vite)</summary>

### [`v5.1.1`](https://togithub.com/vitejs/vite/blob/HEAD/packages/vite/CHANGELOG.md#small511-2024-02-09-small)

-   fix: empty CSS file was output when only .css?url is used ([#&#8203;15846](https://togithub.com/vitejs/vite/issues/15846)) ([b2873ac](https://togithub.com/vitejs/vite/commit/b2873ac)), closes [#&#8203;15846](https://togithub.com/vitejs/vite/issues/15846)
-   fix: skip not only .js but also .mjs manifest entries ([#&#8203;15841](https://togithub.com/vitejs/vite/issues/15841)) ([3d860e7](https://togithub.com/vitejs/vite/commit/3d860e7)), closes [#&#8203;15841](https://togithub.com/vitejs/vite/issues/15841)
-   chore: post 5.1 release edits ([#&#8203;15840](https://togithub.com/vitejs/vite/issues/15840)) ([9da6502](https://togithub.com/vitejs/vite/commit/9da6502)), closes [#&#8203;15840](https://togithub.com/vitejs/vite/issues/15840)

### [`v5.1.0`](https://togithub.com/vitejs/vite/blob/HEAD/packages/vite/CHANGELOG.md#510-2024-02-08)

-   chore: revert [#&#8203;15746](https://togithub.com/vitejs/vite/issues/15746) ([#&#8203;15839](https://togithub.com/vitejs/vite/issues/15839)) ([ed875f8](https://togithub.com/vitejs/vite/commit/ed875f8)), closes [#&#8203;15746](https://togithub.com/vitejs/vite/issues/15746) [#&#8203;15839](https://togithub.com/vitejs/vite/issues/15839)
-   fix: pass `customLogger` to `loadConfigFromFile` (fix [#&#8203;15824](https://togithub.com/vitejs/vite/issues/15824)) ([#&#8203;15831](https://togithub.com/vitejs/vite/issues/15831)) ([55a3427](https://togithub.com/vitejs/vite/commit/55a3427)), closes [#&#8203;15824](https://togithub.com/vitejs/vite/issues/15824) [#&#8203;15831](https://togithub.com/vitejs/vite/issues/15831)
-   fix(deps): update all non-major dependencies ([#&#8203;15803](https://togithub.com/vitejs/vite/issues/15803)) ([e0a6ef2](https://togithub.com/vitejs/vite/commit/e0a6ef2)), closes [#&#8203;15803](https://togithub.com/vitejs/vite/issues/15803)
-   refactor: remove `vite build --force` ([#&#8203;15837](https://togithub.com/vitejs/vite/issues/15837)) ([f1a4242](https://togithub.com/vitejs/vite/commit/f1a4242)), closes [#&#8203;15837](https://togithub.com/vitejs/vite/issues/15837)

</details>

<details>
<summary>pmndrs/zustand (zustand)</summary>

### [`v4.5.0`](https://togithub.com/pmndrs/zustand/releases/tag/v4.5.0)

[Compare Source](https://togithub.com/pmndrs/zustand/compare/v4.4.7...v4.5.0)

This version adds a new capability for SSR/Hydration.

#### What's Changed

-   feat: getInitialState by [@&#8203;TkDodo](https://togithub.com/TkDodo) in [https://github.com/pmndrs/zustand/pull/2277](https://togithub.com/pmndrs/zustand/pull/2277)
-   fix: Add deprecation notice for getServerState() in WithReact type by [@&#8203;charkour](https://togithub.com/charkour) in [https://github.com/pmndrs/zustand/pull/2266](https://togithub.com/pmndrs/zustand/pull/2266)

#### New Contributors

-   [@&#8203;Jontii](https://togithub.com/Jontii) made their first contribution in [https://github.com/pmndrs/zustand/pull/2228](https://togithub.com/pmndrs/zustand/pull/2228)
-   [@&#8203;wherehows](https://togithub.com/wherehows) made their first contribution in [https://github.com/pmndrs/zustand/pull/2239](https://togithub.com/pmndrs/zustand/pull/2239)
-   [@&#8203;ahulterstrom](https://togithub.com/ahulterstrom) made their first contribution in [https://github.com/pmndrs/zustand/pull/2252](https://togithub.com/pmndrs/zustand/pull/2252)
-   [@&#8203;JaeBrian](https://togithub.com/JaeBrian) made their first contribution in [https://github.com/pmndrs/zustand/pull/2267](https://togithub.com/pmndrs/zustand/pull/2267)
-   [@&#8203;CodyCodes95](https://togithub.com/CodyCodes95) made their first contribution in [https://github.com/pmndrs/zustand/pull/2218](https://togithub.com/pmndrs/zustand/pull/2218)

**Full Changelog**: https://github.com/pmndrs/zustand/compare/v4.4.7...v4.5.0

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 4am on Monday" in timezone Europe/Berlin, Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get [config help](https://togithub.com/renovatebot/renovate/discussions) if that's undesired.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Mend Renovate](https://www.mend.io/free-developer-tools/renovate/). View repository job log [here](https://developer.mend.io/github/mheob/ef-calc).